I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ii_eroge_prologue.rpy", line 71, in <module>
    $ set_mode_nvl()
NameError: name 'set_mode_nvl' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/ii_eroge_prologue.rpyc", line 71, in script
  File "C:\Users\Lenovo\renpy-6.99.10-sdk\renpy\ast.py", line 806, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Lenovo\renpy-6.99.10-sdk\renpy\python.py", line 1577, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/ii_eroge_prologue.rpy", line 71, in <module>
    $ set_mode_nvl()
NameError: name 'set_mode_nvl' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
krippy-tan 0.1
